version: "3.9"
name: ula_inventario

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ula_frontend
    restart: unless-stopped
    environment:
      NODE_ENV: development
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.angular
    command: npm start
